#
# Copyright (C) 2009 Ubixum, Inc. 
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

import nitro
from nitro import DeviceInterface, Terminal, Register, SubReg

prom_di = nitro.load_di ( "Microchip/M24XX/M24XX.xml" )
fx2_prom_term = prom_di['M24XX'].clone()
fx2_prom_term.name = 'FX2_PROM'
fx2_prom_term.add_child ( 
    Register ( 
        name='serialnum',
        addr=0xffff-8, # place serial number at last 10 bytes of eeprom
        comment="Location of serial number stored on eeprom.",
        mode="write",
        width=8, # 8 bytes (str type not implemented yet)
        array=8) )


di=DeviceInterface(
    name="Cy7C68013",
    terminal_list=[ 

        Terminal(
            name='FX2',
            comment='Special FX2 functions.  This terminal also gets and sets memory data in the FX2 e600-fdff range.  (Note this does not work with reads, only get/set)', 
            addr=0x100,
            regAddrWidth=16,
            regDataWidth=16,
            register_list = [
                Register(name="version",
                         mode="read",
                         comment="Application Firmware Version"
                ),
                Register(name="usbvid",
                         mode="read",
                         comment="USB Vendor ID" ),
                Register(name="usbpid",
                         mode="read",
                         comment="USB Product ID" ),
                Register(name="usbver",
                         mode="read",
                         comment="USB device descriptor information" ,
                         subregs=[ SubReg ( name="minor",
                                        width=8,
                                        comment="Nitro protocol minor version." ),
                                   SubReg ( name="major",
                                        width=8,
                                        comment="Nitro protocol major version." )
                                  ] )
             ]
        ),

        Terminal(
            name='FX2_SFR',
            comment='Access to FX2 Special function registers.  The register address is the special function register address.', 
            addr=0x101,
            regAddrWidth=16,
            regDataWidth=16,
            register_list = [
                Register(name="IOA",
                         mode="write",
                         addr=0x80,
                         comment="Port A IO",
                         subregs=[
                            SubReg ( name="A0",
                                     width=1,
                                     comment="bit 0"),
                            SubReg ( name="A1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="A2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="A3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="A4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="A5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="A6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="A7",
                                     width=1,
                                     comment="bit 7"),
                         ],
                         ),
                Register(name="OEA",
                         mode="write",
                         addr=0xb2,
                         comment="Output Enable on Port A",
                         subregs=[
                            SubReg ( name="A0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="A1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="A2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="A3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="A4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="A5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="A6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="A7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="IOB",
                         mode="write",
                         addr=0x90,
                         comment="IO on Port B.",
                         subregs=[
                            SubReg ( name="B0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="B1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="B2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="B3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="B4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="B5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="B6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="B7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="OEB",
                         mode="write",
                         addr=0xb3,
                         comment="Output Enable on Port B",
                         subregs=[
                            SubReg ( name="B0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="B1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="B2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="B3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="B4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="B5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="B6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="B7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="IOC",
                         mode="write",
                         addr=0xA0,
                         comment="IO on Port C.",
                         subregs=[
                            SubReg ( name="C0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="C1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="C2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="C3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="C4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="C5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="C6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="C7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="OEC",
                         mode="write",
                         addr=0xb4,
                         comment="Output Enable on Port C",
                         subregs=[
                            SubReg ( name="C0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="C1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="C2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="C3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="C4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="C5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="C6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="C7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="IOD",
                         mode="write",
                         addr=0xB0,
                         comment="IO on Port D.",
                         subregs=[
                            SubReg ( name="D0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="D1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="D2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="D3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="D4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="D5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="D6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="D7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="OED",
                         mode="write",
                         addr=0xb5,
                         comment="Output Enable on Port D",
                         subregs=[
                            SubReg ( name="D0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="D1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="D2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="D3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="D4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="D5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="D6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="D7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="IOE",
                         mode="write",
                         addr=0xB1,
                         comment="IO on Port E.",
                         subregs=[
                            SubReg ( name="E0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="E1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="E2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="E3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="E4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="E5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="E6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="E7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                Register(name="OEE",
                         mode="write",
                         addr=0xb6,
                         comment="Output Enable on Port E",
                         subregs=[
                            SubReg ( name="E0",
                                     width=1,
                                     comment="bit 0" ),
                            SubReg ( name="E1",
                                     width=1,
                                     comment="bit 1"),
                            SubReg ( name="E2",
                                     width=1,
                                     comment="bit 2" ),
                            SubReg ( name="E3",
                                     width=1,
                                     comment="bit 3"),
                            SubReg ( name="E4",
                                     width=1,
                                     comment="bit 4" ),
                            SubReg ( name="E5",
                                     width=1,
                                     comment="bit 5"),
                            SubReg ( name="E6",
                                     width=1,
                                     comment="bit 6" ),
                            SubReg ( name="E7",
                                     width=1,
                                     comment="bit 7"),
                            ],
                         ),
                ],
             ),
             fx2_prom_term
     ]
)


